// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDA2fsDV0exXOsQHZjeEX2S1Uu77K_5Cx0',
    appId: '1:623153253321:web:4caa5d4c394a86ff6cb618',
    messagingSenderId: '623153253321',
    projectId: 'app-iot-tesis',
    authDomain: 'app-iot-tesis.firebaseapp.com',
    databaseURL: 'https://app-iot-tesis-default-rtdb.firebaseio.com',
    storageBucket: 'app-iot-tesis.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2GgBGr1pfVmFMlX4EiEfqQ8DWCujWW90',
    appId: '1:623153253321:android:5b94798be118a8e36cb618',
    messagingSenderId: '623153253321',
    projectId: 'app-iot-tesis',
    databaseURL: 'https://app-iot-tesis-default-rtdb.firebaseio.com',
    storageBucket: 'app-iot-tesis.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD6kQATsiP2ypMUJoo-Q7mXHb1ukCM21s',
    appId: '1:623153253321:ios:8c1694ebdca477586cb618',
    messagingSenderId: '623153253321',
    projectId: 'app-iot-tesis',
    databaseURL: 'https://app-iot-tesis-default-rtdb.firebaseio.com',
    storageBucket: 'app-iot-tesis.appspot.com',
    iosClientId: '623153253321-kuk3401vj5h8l3hkcg6aj9bp2e1h8iec.apps.googleusercontent.com',
    iosBundleId: 'com.example.appIotTesis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAD6kQATsiP2ypMUJoo-Q7mXHb1ukCM21s',
    appId: '1:623153253321:ios:115efc2e2a23a3106cb618',
    messagingSenderId: '623153253321',
    projectId: 'app-iot-tesis',
    databaseURL: 'https://app-iot-tesis-default-rtdb.firebaseio.com',
    storageBucket: 'app-iot-tesis.appspot.com',
    iosClientId: '623153253321-0bduvotqflfpl92566k808e1nruo3i9b.apps.googleusercontent.com',
    iosBundleId: 'com.example.appIotTesis.RunnerTests',
  );
}
